
stopwords = [
    "a", "a's", "able", "about", "above", "according", "accordingly", "across",
    "actually", "after", "afterwards", "again", "against", "ain't", "all",
    "allow", "allows", "almost", "alone", "along", "already", "also",
    "although", "always", "am", "among", "amongst", "an", "and", "another",
    "any", "anybody", "anyhow", "anyone", "anything", "anyway", "anyways",
    "anywhere", "apart", "appear", "appreciate", "appropriate", "are",
    "aren't", "around", "as", "aside", "ask", "asking", "associated", "at",
    "available", "away", "awfully", "b", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
    "believe", "below", "beside", "besides", "best", "better", "between",
    "beyond", "both", "brief", "but", "by", "c", "c'mon", "c's", "came", "can",
    "can't", "cannot", "cant", "cause", "causes", "certain", "certainly",
    "changes", "clearly", "co", "com", "come", "comes", "concerning",
    "consequently", "consider", "considering", "contain", "containing",
    "contains", "corresponding", "could", "couldn't", "course", "currently",
    "d", "definitely", "described", "despite", "did", "didn't", "different",
    "do", "does", "doesn't", "doing", "don't", "done", "down", "downwards",
    "during", "e", "each", "edu", "eg", "eight", "either", "else", "elsewhere",
    "enough", "entirely", "especially", "et", "etc", "even", "ever", "every",
    "everybody", "everyone", "everything", "everywhere", "ex", "exactly",
    "example", "except", "f", "far", "few", "fifth", "first", "five",
    "followed", "following", "follows", "for", "former", "formerly", "forth",
    "four", "from", "further", "furthermore", "g", "get", "gets", "getting",
    "given", "gives", "go", "goes", "going", "gone", "got", "gotten",
    "greetings", "h", "had", "hadn't", "happens", "hardly", "has", "hasn't",
    "have", "haven't", "having", "he", "he's", "hello", "help", "hence", "her",
    "here", "here's", "hereafter", "hereby", "herein", "hereupon", "hers",
    "herself", "hi", "him", "himself", "his", "hither", "hopefully", "how",
    "howbeit", "however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if",
    "ignored", "immediate", "in", "inasmuch", "inc", "indeed", "indicate",
    "indicated", "indicates", "inner", "insofar", "instead", "into", "inward",
    "is", "isn't", "it", "it'd", "it'll", "it's", "its", "itself", "j", "just",
    "k", "keep", "keeps", "kept", "know", "knows", "known", "l", "last",
    "lately", "later", "latter", "latterly", "least", "less", "lest", "let",
    "let's", "like", "liked", "likely", "little", "look", "looking", "looks",
    "ltd", "m", "mainly", "many", "may", "maybe", "me", "mean", "meanwhile",
    "merely", "might", "more", "moreover", "most", "mostly", "much", "must",
    "my", "myself", "n", "name", "namely", "nd", "near", "nearly", "necessary",
    "need", "needs", "neither", "never", "nevertheless", "new", "next", "nine",
    "no", "nobody", "non", "none", "noone", "nor", "normally", "not",
    "nothing", "novel", "now", "nowhere", "o", "obviously", "of", "off",
    "often", "oh", "ok", "okay", "old", "on", "once", "one", "ones", "only",
    "onto", "or", "other", "others", "otherwise", "ought", "our", "ours",
    "ourselves", "out", "outside", "over", "overall", "own", "p", "particular",
    "particularly", "per", "perhaps", "placed", "please", "plus", "possible",
    "presumably", "probably", "provides", "q", "que", "quite", "qv", "r",
    "rather", "rd", "re", "really", "reasonably", "regarding", "regardless",
    "regards", "relatively", "respectively", "right", "s", "said", "same",
    "saw", "say", "saying", "says", "second", "secondly", "see", "seeing",
    "seem", "seemed", "seeming", "seems", "seen", "self", "selves", "sensible",
    "sent", "serious", "seriously", "seven", "several", "shall", "she",
    "should", "shouldn't", "since", "six", "so", "some", "somebody", "somehow",
    "someone", "something", "sometime", "sometimes", "somewhat", "somewhere",
    "soon", "sorry", "specified", "specify", "specifying", "still", "sub",
    "such", "sup", "sure", "t", "t's", "take", "taken", "tell", "tends", "th",
    "than", "thank", "thanks", "thanx", "that", "that's", "thats", "the",
    "their", "theirs", "them", "themselves", "then", "thence", "there",
    "there's", "thereafter", "thereby", "therefore", "therein", "theres",
    "thereupon", "these", "they", "they'd", "they'll", "they're", "they've",
    "think", "third", "this", "thorough", "thoroughly", "those", "though",
    "three", "through", "throughout", "thru", "thus", "to", "together", "too",
    "took", "toward", "towards", "tried", "tries", "truly", "try", "trying",
    "twice", "two", "u", "un", "under", "unfortunately", "unless", "unlikely",
    "until", "unto", "up", "upon", "us", "use", "used", "useful", "uses",
    "using", "usually", "uucp", "v", "value", "various", "very", "via", "viz",
    "vs", "w", "want", "wants", "was", "wasn't", "way", "we", "we'd", "we'll",
    "we're", "we've", "welcome", "well", "went", "were", "weren't", "what",
    "what's", "whatever", "when", "whence", "whenever", "where", "where's",
    "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever",
    "whether", "which", "while", "whither", "who", "who's", "whoever", "whole",
    "whom", "whose", "why", "will", "willing", "wish", "with", "within",
    "without", "won't", "wonder", "would", "would", "wouldn't", "x", "y",
    "yes", "yet", "you", "you'd", "you'll", "you're", "you've", "your",
    "yours", "yourself", "yourselves", "z", "zero"
]

substitutions = [
    (r"\b(im|i'm)\b", "i am"),
    (r"\b(id|i'd)\b", "i would"),
    (r"\b(i'll)\b", "i will"),
    (r"\bbf|b/f\b", "boyfriend"),
    (r"\bgf|g/f\b", "girlfriend"),
    (r"\byoure\b", "you are"),
    (r"\b(dont|don't)\b", "do not"),
    (r"\b(didnt|didn't)\b", "did not"),
    (r"\b(wasnt|wasn't)\b", "was not"),
    (r"\b(isnt|isn't)\b", "is not"),
    (r"\b(arent|aren't)\b", "are not"),
    (r"\b(werent|weren't)\b", "were not"),
    (r"\b(havent|haven't)\b", "have not"),
    (r"\b(couldnt|couldn't)\b", "could not"),
    (r"\b(hadnt|hadn't)\b", "had not"),
    (r"\b(wouldnt|wouldn't)\b", "would not"),
    (r"\bgotta\b", "have to"),
    (r"\bgonna\b", "going to"),
    (r"\bwanna\b", "want to"),
    (r"\b(kinda|kind of)\b", ""),
    (r"\b(sorta|sort of)\b", ""),
    (r"\b(dunno|donno)\b", "do not know"),
    (r"\b(cos|coz|cus|cuz)\b", "because"),
    (r"\bfave\b", "favorite"),
    (r"\bhubby\b", "husband"),
    (r"\bheres\b", "here is"),
    (r"\btheres\b", "there is"),
    (r"\bwheres\b", "where is"),
    # Common acronyms, abbreviations and slang terms
    (r"\birl\b", "in real life"),
    (r"\biar\b", "in a relationship"),
    (r"\btotes\b", "totally"),
    (r","," and "),
    # Remove fluff phrases
    (r"\b(btw|by the way)\b", ""),
    (r"\b(tbh|to be honest)\b", ""),
    (r"\b(imh?o|in my( humble)? opinion)\b", ""),
    # Default POS tagger seems to always tag "like"
    # (and sometimes "love") as a noun - this is a bandaid fix for now
    (r"\bprefer\b", ""),
    (r"\b(like|love)\b", "prefer"),
]

skip_attributes = [
    "supporter", "believer", "gender", "backer", "sucker", "chapter",
    "passenger", "super", "water", "sitter", "killer", "stranger",
    "monster", "leather", "holder", "creeper", "shower", "member",
    "wonder", "hungover", "sniper", "silver", "beginner", "lurker",
    "loser", "number", "stupider", "outlier", "molester", "hitler", "beer",
    "cucumber", "earlier", "denier", "lumber", "hamster", "abuser",
    "murderer", "dealer", "consumer", "wallpaper", "paper", "madder",
    "uber", "computer", "rubber",
    "door", "liquor", "traitor", "favor",
    "year", "ear", "liar",
    "rapist", "racist", "misogynist", "apologist", "sexist",
    "satan", "batman", "veteran", "ban",
    "hypocrite", "candidate",
    "lot", "faggot", "teapot", "shot", "foot", "idiot", "bigot", "robot"
]
